; FasterEdge MCU (Arduino Uno R3) — PlatformIO 配置
; 裸机 C（avr-gcc），无 Arduino 框架依赖：寄存器级驱动
[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

build_flags =
    -DF_CPU=16000000L
